version: '3'
services:
  web:
    container_name: 'trendyolcase-app'
    image: 'trendyolcase'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:80'
    depends_on:
      - 'postgres'
    networks:
      - trendyolcase-network  

  postgres:
    ports:
      - '5432:5432'
    container_name: trendyolcase-postgresql
    restart: always
    environment:
        POSTGRES_USER: trendyol # The PostgreSQL user (useful to connect to the database)
        POSTGRES_PASSWORD: trendyol # The PostgreSQL password (useful to connect to the database)
        POSTGRES_DB: trendyoldb # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - 'trendyol-postgresql-volume:/var/lib/postgresql/data'
    image: 'postgres:latest'
    networks:
      - trendyolcase-network

volumes:
  trendyol-postgresql-volume:

networks:
  trendyolcase-network:
    driver: bridge